[client]
showSidebarNavigation = false

[ui]
hideSidebarNav = true

[theme]
base="light"
primaryColor="#ed665f"
secondaryBackgroundColor="#faeee1"
backgroundColor="#fff"
textColor="#333"
font="Karla:https://fonts.googleapis.com/css2?family=Karla:ital,wght@0,200..800;1,200..800&display=swap"


